#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: arm relocs'
FILE=../../bins/elf/analysis/arm-relocs
ARGS=''
CMDS="ir*~reloc?
ir*~!1"
EXPECT='11
fs relocs
f reloc.r0 @ 0x08000034
f reloc.r2 @ 0x0800003c
f reloc.r3 @ 0x08000040
f reloc.r4 @ 0x08000044
f reloc.r0 @ 0x0800004c
f reloc.r2 @ 0x08000054
f reloc.r3 @ 0x08000058
f reloc.r4 @ 0x0800005c
'
run_test

NAME='ELF: ppc relocs'
FILE=../../bins/elf/hello.ppc
ARGS=''
CMDS="ii;s main;af;pdsf"
EXPECT='[Imports]
   1 0x10020064  GLOBAL    FUNC printf
   2 0x10020074    WEAK  NOTYPE __gmon_start__
   3 0x10020084  GLOBAL    FUNC __libc_start_main
;-- main:
0x100004a0 str.Simple_PPC_program. str.Simple_PPC_program.
0x100004a4 sym.imp.printf
'
run_test
